catalog:
  '@shikijs/transformers': ^2.5.0
  '@shikijs/vitepress-twoslash': ^2.5.0
  '@typescript-eslint/parser': ^8.24.1
  '@typescript-eslint/utils': ^8.24.1
  '@vitest/coverage-v8': ^3.0.6
  twoslash: ^0.2.12
  twoslash-eslint: ^0.2.12
  typescript-eslint: ^8.24.1
  vitest: ^3.0.6
packages:
  - docs
