packages:
  - .
  - docs
catalog:
  '@shikijs/transformers': ^3.2.1
  '@shikijs/vitepress-twoslash': ^3.2.1
  '@typescript-eslint/parser': ^8.27.0
  '@typescript-eslint/utils': ^8.27.0
  '@vitest/coverage-v8': ^3.0.9
  twoslash: ^0.3.1
  twoslash-eslint: ^0.3.1
  typescript-eslint: ^8.27.0
  vitest: ^3.0.9
overrides:
  '@shikijs/core': ^3.2.0
  '@shikijs/markdown-it': ^3.1.0
  '@shikijs/rehype': ^3.1.0
  '@shikijs/transformers': ^3.2.0
  '@shikijs/types': ^3.2.0
  esbuild: ^0.25.1
  shiki: ^3.2.0
onlyBuiltDependencies:
  - esbuild
