catalog:
  '@shikijs/transformers': ^3.1.0
  '@shikijs/vitepress-twoslash': ^3.1.0
  '@typescript-eslint/parser': ^8.26.0
  '@typescript-eslint/utils': ^8.26.0
  '@vitest/coverage-v8': ^3.0.8
  twoslash: ^0.3.1
  twoslash-eslint: ^0.3.1
  typescript-eslint: ^8.26.0
  vitest: ^3.0.8
onlyBuiltDependencies:
  - esbuild
packages:
  - .
  - docs
