packages:
  - .
  - docs

overrides:
  esbuild: ^0.25.5

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  '@es-joy/jsdoccomment@0.51.1': patches/@es-joy__jsdoccomment@0.51.1.patch
