catalog:
  '@shikijs/transformers': ^3.0.0
  '@shikijs/vitepress-twoslash': ^3.0.0
  '@typescript-eslint/parser': ^8.25.0
  '@typescript-eslint/utils': ^8.25.0
  '@vitest/coverage-v8': ^3.0.7
  twoslash: ^0.2.12
  twoslash-eslint: ^0.2.12
  typescript-eslint: ^8.25.0
  vitest: ^3.0.7
packages:
  - docs
