catalog:
  '@shikijs/transformers': ^2.4.1
  '@shikijs/vitepress-twoslash': ^2.4.1
  '@typescript-eslint/parser': ^8.24.0
  '@typescript-eslint/utils': ^8.24.0
  '@vitest/coverage-v8': ^3.0.5
  twoslash: ^0.2.12
  twoslash-eslint: ^0.2.12
  typescript-eslint: ^8.24.0
  vitest: ^3.0.5
packages:
  - docs
