packages:
  - .
  - docs
catalog:
  '@iconify-json/ri': ^1.2.5
  '@ntnyq/eslint-config': ^4.1.0
  '@ntnyq/prettier-config': ^2.0.0
  '@ntnyq/utils': ^0.6.4
  '@shikijs/transformers': ^3.3.0
  '@shikijs/vitepress-twoslash': ^3.3.0
  '@types/markdown-it-container': ^2.0.10
  '@types/node': ^22.15.3
  '@typescript-eslint/parser': ^8.31.0
  '@typescript-eslint/utils': ^8.31.0
  '@vitest/coverage-v8': ^3.1.2
  bumpp: ^10.1.0
  eslint: ^9.25.1
  eslint-plugin-eslint-plugin: ^6.4.0
  eslint-vitest-rule-tester: ^2.2.0
  husky: ^9.1.7
  markdown-it-container: ^4.0.0
  nano-staged: ^0.8.0
  npm-run-all2: ^7.0.2
  prettier: ^3.5.3
  twoslash: ^0.3.1
  twoslash-eslint: ^0.3.1
  typescript: ^5.8.3
  typescript-eslint: ^8.31.0
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.12
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.3
  vitepress: ^2.0.0-alpha.5
  vitepress-plugin-group-icons: ^1.5.2
  vitest: ^3.1.2
  vue: ^3.5.13
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - esbuild
