packages:
  - docs

allowBuilds:
  esbuild: true
  unrs-resolver: true

ignoreWorkspaceRootCheck: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@rolldown/binding-android-arm-eabi@1.2.6'
  - '@rolldown/binding-android-arm64@1.2.6'
  - '@rolldown/binding-darwin-arm64@1.2.6'
  - '@rolldown/binding-darwin-x64@1.2.6'
  - '@rolldown/binding-freebsd-x64@1.2.6'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.6'
  - '@rolldown/binding-linux-arm64-gnu@1.2.6'
  - '@rolldown/binding-linux-arm64-musl@1.2.6'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.6'
  - '@rolldown/binding-linux-s390x-gnu@1.2.6'
  - '@rolldown/binding-linux-x64-gnu@1.2.6'
  - '@rolldown/binding-linux-x64-musl@1.2.6'
  - '@rolldown/binding-openharmony-arm64@1.2.6'
  - '@rolldown/binding-win32-arm64-msvc@1.2.6'
  - '@rolldown/binding-win32-x64-msvc@1.2.6'
  - '@types/node@26.4.0'
  - '@ungap/structured-clone@1.3.4'
  - bumpp@12.2.2
  - magic-string@1.2.3
  - rolldown@1.2.6
pmOnFail: warn
